In [324]:
import numpy as pd
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [325]:
from sklearn import preprocessing
encoder = preprocessing.LabelEncoder()

In [326]:
df = pd.read_csv('/content/Data_file.xlsx - Data.csv')
test_data = pd.read_csv('/content/Test_data_file.xlsx - Prediction.csv')
df.head()

,S.No.,College,Role,City type,Previous CTC,Previous job changes,Graduation marks,Exp (Months),CTC
0,1,Tier 1,Manager,Non-Metro,"55,523.00",3,66,19,"71,406.58"
1,2,Tier 2,Executive,Metro,"57,081.00",1,84,18,"68,005.87"
2,3,Tier 2,Executive,Metro,"60,347.00",2,52,28,"76,764.02"
3,4,Tier 3,Executive,Metro,"49,010.00",2,81,33,"82,092.39"
4,5,Tier 3,Executive,Metro,"57,879.00",4,74,32,"73,878.10"

In [327]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   S.No.                 1338 non-null   int64
 1   College               1338 non-null   object
 2   Role                  1338 non-null   object
 3   City type             1338 non-null   object
 4   Previous CTC          1338 non-null   object
 5   Previous job changes  1338 non-null   int64
 6   Graduation marks      1338 non-null   int64
 7   Exp (Months)          1338 non-null   int64
 8   CTC                   1338 non-null   object
dtypes: int64(4), object(5)
memory usage: 94.2+ KB

In [328]:
df['College'].value_counts()

Tier 1    649
Tier 2    364
Tier 3    325
Name: College, dtype: int64

**For Test Dataset**

In [329]:
test_data.head()

,College,Role,City type,College_T1,College_T2,Role_Manager,City_Metro,previous CTC,previous job changes,Graduation marks,Exp,Actual CTC,Predicted CTC
0,Tier 1,Manager,Non-Metro,1,0,1,0,55523,3,66,19,71406.57653,NaN
1,Tier 2,Executive,Metro,0,1,0,1,57081,1,84,18,68005.87063,NaN
2,Tier 2,Executive,Metro,0,1,0,1,60347,2,52,28,76764.02028,NaN
3,Tier 3,Executive,Metro,0,0,0,1,49010,2,81,33,82092.38688,NaN
4,Tier 3,Executive,Metro,0,0,0,1,57879,4,74,32,73878.09773,NaN

In [330]:
test_data.rename(columns = {'City type':'City_Type'}, inplace = True)

In [331]:
test_data.rename(columns = {'previous CTC':'Previous_CTC'}, inplace = True)

In [332]:
test_data.rename(columns = {'previous job changes':'Previous_Job_Changes'}, inplace = True)

In [333]:
test_data.rename(columns = {'Graduation marks':'Graduation_marks'}, inplace = True)

In [334]:
test_data.rename(columns = {'Actual CTC':'Actual_CTC'}, inplace = True)

In [335]:
test_data.rename(columns = {'Predicted CTC':'Predicted_CTC'}, inplace = True)

In [336]:
test_data.drop(columns=['Predicted_CTC'],inplace = True)

In [337]:
test_data['Role']= encoder.fit_transform(test_data['Role'])
test_data['City_Type']= encoder.fit_transform(test_data['City_Type'])

In [338]:
test_data['College']= encoder.fit_transform(test_data['College'])

In [339]:
test_data.head()

,College,Role,City_Type,College_T1,College_T2,Role_Manager,City_Metro,Previous_CTC,Previous_Job_Changes,Graduation_marks,Exp,Actual_CTC
0,0,1,1,1,0,1,0,55523,3,66,19,71406.57653
1,1,0,0,0,1,0,1,57081,1,84,18,68005.87063
2,1,0,0,0,1,0,1,60347,2,52,28,76764.02028
3,2,0,0,0,0,0,1,49010,2,81,33,82092.38688
4,2,0,0,0,0,0,1,57879,4,74,32,73878.09773

**For Train Dataset**

In [340]:
df.rename(columns = {'City type':'City_Type'}, inplace = True)

In [341]:
df.rename(columns = {'Previous CTC':'Previous_CTC'}, inplace = True)

In [342]:
df.rename(columns = {'Previous job changes':'Previous_job_changes'}, inplace = True)

In [343]:
df.rename(columns = {'Graduation marks':'Graduation_marks'}, inplace = True)

In [344]:
df.rename(columns = {'Exp (Months)':'Exp_Months'}, inplace = True)

In [345]:
df.head()

,S.No.,College,Role,City_Type,Previous_CTC,Previous_job_changes,Graduation_marks,Exp_Months,CTC
0,1,Tier 1,Manager,Non-Metro,"55,523.00",3,66,19,"71,406.58"
1,2,Tier 2,Executive,Metro,"57,081.00",1,84,18,"68,005.87"
2,3,Tier 2,Executive,Metro,"60,347.00",2,52,28,"76,764.02"
3,4,Tier 3,Executive,Metro,"49,010.00",2,81,33,"82,092.39"
4,5,Tier 3,Executive,Metro,"57,879.00",4,74,32,"73,878.10"

In [346]:
df['Role'].value_counts()

Executive    1064
Manager       274
Name: Role, dtype: int64

In [347]:
df['City_Type'].value_counts()

Metro        676
Non-Metro    662
Name: City_Type, dtype: int64

In [348]:

df['College']= encoder.fit_transform(df['College'])

df['College'].unique()

array([0, 1, 2])

In [349]:
df['Role']= encoder.fit_transform(df['Role'])
df['City_Type']= encoder.fit_transform(df['City_Type'])

In [350]:
df.head()

,S.No.,College,Role,City_Type,Previous_CTC,Previous_job_changes,Graduation_marks,Exp_Months,CTC
0,1,0,1,1,"55,523.00",3,66,19,"71,406.58"
1,2,1,0,0,"57,081.00",1,84,18,"68,005.87"
2,3,1,0,0,"60,347.00",2,52,28,"76,764.02"
3,4,2,0,0,"49,010.00",2,81,33,"82,092.39"
4,5,2,0,0,"57,879.00",4,74,32,"73,878.10"

In [351]:
df['CTC'] = df['CTC'].str.replace(',', '').astype(float)
df['Previous_CTC'] = df['Previous_CTC'].str.replace(',', '').astype(float)
# test_data['CTC'] = test_data['CTC'].str.replace(',', '').astype(float)

In [352]:
df.head()

,S.No.,College,Role,City_Type,Previous_CTC,Previous_job_changes,Graduation_marks,Exp_Months,CTC
0,1,0,1,1,55523.0,3,66,19,71406.58
1,2,1,0,0,57081.0,1,84,18,68005.87
2,3,1,0,0,60347.0,2,52,28,76764.02
3,4,2,0,0,49010.0,2,81,33,82092.39
4,5,2,0,0,57879.0,4,74,32,73878.10

In [353]:
x = df.drop(columns = 'CTC',axis = 1)
y = df['CTC']

In [354]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 20)

In [ ]:
model = LinearRegression()
model.fit(x_train, y_train)

In [356]:
y_pred = model.predict(x_test)

In [357]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error (MSE): {mse}")

Mean Squared Error (MSE): 67358196.29289025

In [358]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.5796510590670594

**Test Data Evaluation**

In [360]:
X = test_data.drop(columns = 'Actual_CTC',axis = 1)
Y = test_data['Actual_CTC']

In [361]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.3,random_state = 20)

In [ ]:
modeltestdata = LinearRegression()
modeltestdata.fit(X_train, Y_train)

In [363]:
y_prediction = modeltestdata.predict(X_test)

In [364]:
msetestdata = mean_squared_error(Y_test, y_prediction)
print(f"Mean Squared Error (MSE): {msetestdata}")

Mean Squared Error (MSE): 64232915.09461605

In [365]:
r2_score(Y_test,y_prediction)

0.5991543853267601